macro(add_submodule_dep)
    if(${ARGC} GREATER 2)
        message(FATAL "macro add_submodule_dep take only one argument, the name of the package")
    else()
        message(STATUS "Looking for ${ARGV0}")
        list(APPEND CMAKE_MESSAGE_INDENT "  ")
        if(${USE_SUBMODULE_${ARGV0}})
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/external/${ARGV0}/CMakeLists.txt")
                message(STATUS "Using subdirectory")
                add_subdirectory("external/${ARGV0}")
            else()
                message(FATAL "You want to use submodule ${ARGV0} but it is not initialize, use 'git submodule update --init'")
            endif()
        else()
            message(STATUS "Using find_package ${ARGV0} ")
            find_package(${ARGV0} REQUIRED)
        endif()
        list(POP_BACK CMAKE_MESSAGE_INDENT )
    endif()
endmacro()
